import { Button, VerticalBox, GridBox } from "std-widgets.slint";
import { left-panel } from "left-panel.slint";
import { sheet } from "sheet.slint";


    
    

export component AppWindow inherits Window {
    width: 850px;
    height: 800px;

     
    Rectangle {
        //width: 800px;
       //height: 800px;
        background: lightblue;
        border-width: 3px;
        border-color: black;
        border-radius: 12px;

        left-panel {}
        sheet {}
    }     
}

    
