import { Button-1, Button-2 } from "buttons.slint";
import { GridBox, Button } from "std-widgets.slint";
export component left-panel {

    
    Rectangle {
        x:-405px;
        width: 185px;
        height: 770px;
        background: #abc1cf;
        border-radius: 12px;
        border-width: 3px;
        border-color: black;

        VerticalLayout {
           // padding: 15px;
            Button-1 {}
            Button-1 {}
            Button-1 {}

            HorizontalLayout {
            
               
            }
        }
    }
}